/* Phoenix AI system registry.
 * Homepage featured cards and the full systems catalog read from this file.
 * Keep public copy de-identified and free of internal implementation details.
 */

window.EXPERIENCE_SOLUTIONS = [
  {
    id: "central_kitchen_operations_guard",
    slug: "central-kitchen-ai-agent",
    title: "中央廚房營運防護台",
    short_title: "營運防護台",
    subtitle: "把履約事件、門市開單與總部例外治理收成可驗證閉環",
    status: "Pilot-ready Sandbox",
    maturity: "Pilot Ready",
    access_type: "公開預覽／預約 Demo",
    featured: true,
    featured_order: 1,
    category: ["營運治理", "餐飲"],
    industries: ["餐飲連鎖", "中央廚房", "零售連鎖"],
    page_variant: "operations",
    showcase_type: "dual-workbench",
    demo_duration: "15 分鐘",
    highlights: [
      "履約訊號進入門市今日必做，顧客不必登入系統",
      "結構化動作卡經規則評分；Pro 可自決或送總部審核",
      "核准後產出對客文案與 ERP／POS 沙盒預覽"
    ],
    sections: ["event-flow", "dual-workbench", "tier-ladder", "boundaries", "pilot-cta"],
    compliance_note: "Sandbox Demo；對客通知與 ERP／POS payload 僅為模擬預覽，不寫入正式系統。",
    cta_text: "查看營運防護台",
    cta_href: "./experience/central-kitchen-ai-agent/index.html",
    catalog_cta_href: "./central-kitchen-ai-agent/index.html",
    pilot_program_text: "預約 15 分鐘 Demo",
    pilot_program_href: "./contact.html?request_type=central_kitchen_demo&utm_source=site&utm_medium=central_kitchen&utm_campaign=central_kitchen_demo&utm_content=flagship",
    catalog_pilot_program_href: "../contact.html?request_type=central_kitchen_demo&utm_source=site&utm_medium=central_kitchen&utm_campaign=central_kitchen_demo&utm_content=systems_catalog",
    primary_action: "pilot",
    contact_category: "experience_cta",
    contact_label: "experience_solution_view",
    updated_at: "2026-07-13"
  },
  {
    id: "diagnostic_workbench",
    slug: "diagnostic-workbench",
    title: "企業問題診斷與決策交付工作台",
    short_title: "診斷工作台",
    subtitle: "把雜亂經營痛點收成可審閱、可重複驗證的決策交付工作流",
    status: "Design-partner Pilot",
    maturity: "Pilot Ready",
    access_type: "Controlled Sandbox",
    featured: true,
    featured_order: 2,
    category: ["決策交付", "知識治理"],
    industries: ["製造業", "供應鏈", "跨產業"],
    page_variant: "consulting-delivery",
    showcase_type: "report-workflow",
    demo_duration: "30–45 分鐘",
    highlights: [
      "從雜亂經營痛點到結構化診斷章節與決策矩陣",
      "知識匹配保留統計與可解釋理由，顧問負責判斷",
      "正式報告、評估與知識回寫形成完整交付閉環"
    ],
    sections: ["workflow", "report-preview", "knowledge-loop", "boundaries", "pilot-cta"],
    compliance_note: "示範與 Pilot 使用匿名或受控案件資料；公開網站不展示真實客戶內容。",
    cta_text: "查看診斷工作台",
    cta_href: "./diagnostic-workbench/index.html",
    catalog_cta_href: "../diagnostic-workbench/index.html",
    pilot_program_text: "預約 30–45 分鐘 Demo",
    pilot_program_href: "./contact.html?request_type=diagnostic_demo&utm_source=site&utm_medium=workbench&utm_campaign=diagnostic_demo&utm_content=flagship",
    catalog_pilot_program_href: "../contact.html?request_type=diagnostic_demo&utm_source=site&utm_medium=workbench&utm_campaign=diagnostic_demo&utm_content=systems_catalog",
    primary_action: "detail",
    contact_category: "experience_cta",
    contact_label: "experience_solution_view",
    updated_at: "2026-07-13"
  },
  {
    id: "phoenix_auditable_ai_workflow",
    slug: "phoenix-auditable-ai-workflow",
    title: "Phoenix 可稽核 AI 工作流",
    short_title: "開源工作流",
    subtitle: "把政策防護、引用證據、人工覆核與稽核事件組成可檢驗的企業 AI 參考架構",
    status: "Open Source v0.1.0",
    maturity: "Open Source Reference",
    access_type: "Public GitHub / Local Reference",
    featured: true,
    featured_order: 3,
    category: ["AI 治理", "開源參考架構"],
    industries: ["資訊與稽核", "企業治理", "跨產業"],
    page_variant: "governance-reference",
    showcase_type: "open-source-showcase",
    demo_duration: "60–90 秒",
    highlights: [
      "Input 與 Output Policy 規則核對",
      "政策衝突攔截與 Human-in-the-loop 人工覆核",
      "Markdown 引用驗證與可查詢的 SQLite 稽核事件"
    ],
    sections: ["portfolio-chain", "workflow", "evidence", "service-boundary", "audience", "limitations", "pilot-cta"],
    compliance_note: "本機 Mock-first 參考架構；使用合成資料，非生產環境認證，稽核事件不具密碼學不可竄改保證。",
    cta_text: "查看開源系統展示",
    cta_href: "./experience/phoenix-auditable-ai-workflow/index.html",
    catalog_cta_href: "./phoenix-auditable-ai-workflow/index.html",
    pilot_program_text: "預約 AI 治理與導入診斷",
    pilot_program_href: "./contact.html?request_type=auditable_ai_demo&utm_source=site&utm_medium=open_source_showcase&utm_campaign=phoenix_auditable_ai_flow&utm_content=homepage_card",
    catalog_pilot_program_href: "../contact.html?request_type=auditable_ai_demo&utm_source=site&utm_medium=open_source_showcase&utm_campaign=phoenix_auditable_ai_flow&utm_content=systems_catalog",
    primary_action: "pilot",
    contact_category: "experience_cta",
    contact_label: "experience_solution_view",
    updated_at: "2026-07-13"
  },
  {

    id: "enterprise_rag_foundation",
    slug: "enterprise-rag-foundation",
    title: "Enterprise RAG Foundation",
    short_title: "RAG Foundation",
    subtitle: "鳳凰企業 RAG Foundation 導入服務：每企業隔離、可引用、可拒答——先證明能力，再受控導入（不公開標價）",
    status: "Foundation 1.0.0 Reference",
    maturity: "Synthetic Reference",
    access_type: "Private GitHub / Local Reference",
    featured: true,
    featured_order: 4,
    category: ["知識治理", "RAG", "客服草稿"],
    industries: ["製造業", "售後服務", "跨產業知識庫"],
    page_variant: "rag-foundation",
    showcase_type: "foundation-reference",
    demo_duration: "10 分鐘",
    highlights: [
      "一企業一 runtime，請求不可切換租戶",
      "引用可追溯；證據不足則拒答或轉人工",
      "空白模板 fail-closed；預設不自動對外發送"
    ],
    sections: ["hero", "capabilities", "boundaries", "t1-t3", "checklist", "pilot-cta"],
    compliance_note: "Synthetic／reference 基線（v1.0.0）；非客戶 production、非企業 SSO 已完成、非零幻覺保證。",
    cta_text: "查看服務說明",
    cta_href: "./services/enterprise-rag-foundation.html",
    catalog_cta_href: "../services/enterprise-rag-foundation.html",
    pilot_program_text: "預約 30 分鐘評估",
    pilot_program_href: "./contact.html?request_type=rag_foundation_assessment&utm_source=site&utm_medium=rag_foundation&utm_campaign=rag_foundation_v1&utm_content=flagship",
    catalog_pilot_program_href: "../contact.html?request_type=rag_foundation_assessment&utm_source=site&utm_medium=rag_foundation&utm_campaign=rag_foundation_v1&utm_content=systems_catalog",
    primary_action: "pilot",
    contact_category: "experience_cta",
    contact_label: "experience_solution_view",
    updated_at: "2026-07-27"
  },
  {
    id: "ledger_assist",
    slug: "ledger-assist",
    title: "Ledger-Assist 發票收件與檢核系統",
    short_title: "憑證檢核系統",
    subtitle: "客戶 LINE 上傳發票、事務所 LINE 內檢核修正；每所獨立私有部署，正式憑證與稽核記錄留在事務所。",
    status: "Sandbox Demo",
    maturity: "Sandbox Demo Ready",
    access_type: "合成展示／預約體驗",
    featured: true,
    featured_order: 4,
    category: ["憑證檢核", "會計事務所"],
    industries: ["會計師事務所", "記帳士事務所", "稅務服務"],
    page_variant: "line-invoice-workflow",
    showcase_type: "synthetic-demo",
    demo_duration: "15 分鐘",
    highlights: [
      "客戶用 LINE 上傳發票，事務所在 LINE 內檢核、修正與確認",
      "AI 只產出可覆核候選，Pilot 期間須人工核准後才匯出",
      "每家事務所獨立私有部署，正式憑證、覆核狀態與稽核記錄留在事務所控制環境"
    ],
    sections: ["line-flow", "review-workflow", "private-deployment", "boundaries", "pilot-cta"],
    compliance_note: "Sandbox Demo：展示使用合成資料，不含真實客戶憑證；正式部署為每家事務所獨立私有部署。",
    cta_text: "查看 Ledger-Assist 展示",
    cta_href: "./experience/ledger-assist/index.html",
    catalog_cta_href: "./ledger-assist/index.html",
    pilot_program_text: "預約私有工作流程評估",
    pilot_program_href: "./contact.html?request_type=ledger_assist_assessment&utm_source=site&utm_medium=ledger_assist&utm_campaign=ledger_assist_v2&utm_content=flagship",
    catalog_pilot_program_href: "../contact.html?request_type=ledger_assist_assessment&utm_source=site&utm_medium=ledger_assist&utm_campaign=ledger_assist_v2&utm_content=systems_catalog",
    primary_action: "pilot",
    contact_category: "experience_cta",
    contact_label: "experience_solution_view",
    updated_at: "2026-08-09"
  },
  {
    id: "ai_lawyer_workbench",
    slug: "ai-lawyer-workbench",
    title: "AI 律師工作台（Matter OS）",
    short_title: "AI 律師工作台",
    subtitle: "給台灣律師事務所的 Matter-centric AI 工作台：多案並行、期限紅線集中管理、人機雙簽——每一案一個可控的 AI 助理團隊，輸出必經律師簽核，引用必能點回法源。",
    status: "Synthetic Demo",
    maturity: "Synthetic Demo Ready",
    access_type: "合成展示／預約體驗",
    featured: true,
    featured_order: 6,
    category: ["律師事務所", "案件管理", "期限引擎"],
    industries: ["個人律師事務所", "中小型律師事務所", "法律服務"],
    page_variant: "ai-lawyer-workbench",
    showcase_type: "synthetic-demo",
    demo_duration: "10 分鐘",
    highlights: [
      "收案自動利益衝突檢核（律師倫理 §31）；同一訟爭事件兩造不得同時受任",
      "雙軌期限引擎：上訴 20 日等不變期間為紅線、系統不可改；T-14/7/3 自動提醒",
      "AI 只做爭點表與書狀大綱；書狀類文件強制雙人覆核，引用必附卷宗頁碼"
    ],
    sections: ["hero", "capabilities", "boundaries", "six-step-flow", "pilot-cta"],
    compliance_note: "展示採合成案件／流程；正式導入依客戶環境、權限與驗收規格完成。AI 草稿須經律師覆核，最終法律判斷與署名由律師負責。",
    cta_text: "查看 AI 律師工作台展示",
    cta_href: "./experience/ai-lawyer-workbench/index.html",
    catalog_cta_href: "./ai-lawyer-workbench/index.html",
    pilot_program_text: "預約私有工作流程評估",
    pilot_program_href: "./contact.html?request_type=ai_lawyer_assessment&utm_source=site&utm_medium=ai_lawyer_workbench&utm_campaign=ai_lawyer_v2&utm_content=flagship",
    catalog_pilot_program_href: "../contact.html?request_type=ai_lawyer_assessment&utm_source=site&utm_medium=ai_lawyer_workbench&utm_campaign=ai_lawyer_v2&utm_content=systems_catalog",
    primary_action: "pilot",
    contact_category: "experience_cta",
    contact_label: "experience_solution_view",
    updated_at: "2026-08-10"
  },
  {
    id: "ai_allocation_os",
    slug: "ai-allocation-os",
    title: "AI Allocation OS 企業 AI 投資決策工作台",
    short_title: "投資決策工作台",
    subtitle: "以 Capital Decision Sprint 顧問服務，把 AI 投資決策收成可稽核決策包：候選篩選、深度 Underwriting、風險 Gate 與決策紀錄，全程留痕。",
    status: "Consulting Offer｜開放預約",
    maturity: "Offer v1.1",
    access_type: "預約 Capital Decision Sprint",
    featured: true,
    featured_order: 5,
    category: ["AI 投資決策", "顧問服務"],
    industries: ["零售／電商", "B2C 服務業", "客服營運"],
    page_variant: "capital-decision",
    showcase_type: "decision-sprint",
    demo_duration: "30–45 分鐘",
    highlights: [
      "最多 5 個候選案篩選、3 個深度 Underwriting，每案產出三軸決策與理由",
      "Funding／Repair／Reassessment Gate 與 T0/T1/T2 決策快照，決策理由版本化留痕",
      "Committee Pack 與決策紀錄版本化交付；評分不因 Phoenix 是否承接後續實作而改變"
    ],
    sections: ["sprint-flow", "gate-model", "deliverables", "boundaries", "pilot-cta"],
    compliance_note: "顧問服務：提供決策支援與分析，案例均去識別化；實際成效依執行結果與驗收數據評估，最終決策權與責任由客戶承擔。",
    cta_text: "查看決策工作台",
    cta_href: "./experience/ai-allocation-os/index.html",
    catalog_cta_href: "./ai-allocation-os/index.html",
    pilot_program_text: "預約 30–45 分鐘說明",
    pilot_program_href: "./contact.html?request_type=capital_sprint_info&utm_source=site&utm_medium=ai_allocation_os&utm_campaign=capital_sprint&utm_content=flagship",
    catalog_pilot_program_href: "../contact.html?request_type=capital_sprint_info&utm_source=site&utm_medium=ai_allocation_os&utm_campaign=capital_sprint&utm_content=systems_catalog",
    primary_action: "pilot",
    contact_category: "experience_cta",
    contact_label: "experience_solution_view",
    updated_at: "2026-08-09"  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = window.EXPERIENCE_SOLUTIONS;
}
